Cosmology:
  H0: 71.0
  Ob0: 0.0448
  Om0: 0.2648
  n_s: 0.963
  sigma8: 0.8
MW_extinction_values:
  a_v:
    mode: data
  r_v:
    mode: constant
    value: 3.1
# catalog_dir: /lus/eagle/projects/RomanDESC/roman_rubin_cats_v1.1.2_faint
catalog_dir: /hpc/group/cosmology/OpenUniverse2024/roman_rubin_cats_v1.1.2_faint
catalog_name: skyCatalog
galaxy_magnitude_cut: 32.0
knots_magnitude_cut: 27.0
object_types:
  bulge_basic:
    MW_extinction: F19
    internal_extinction: CCM
    parent: galaxy
    sed_model: tophat
    spatial_model: sersic2D
    subtype: bulge
  diffsky_bulge:
    MW_extinction: F19
    internal_extinction: CCM
    parent: diffsky_galaxy
    sed_model: TBD
    spatial_model: sersic2D
    subtype: bulge
  diffsky_disk:
    MW_extinction: F19
    internal_extinction: CCM
    parent: diffsky_galaxy
    sed_model: TBD
    spatial_model: sersic2D
    subtype: disk
  diffsky_galaxy:
    area_partition:
      nside: 32
      ordering: ring
      type: healpix
    composite:
      bulge: required
      disk: required
      knots: optional
    data_file_type: parquet
    file_template: galaxy_(?P<healpix>\d+).parquet
    flux_file_template: galaxy_flux_(?P<healpix>\d+).parquet
    sed_file_template: galaxy_sed_(?P<healpix>\d+).hdf5
  diffsky_knots:
    MW_extinction: F19
    internal_extinction: CCM
    parent: diffsky_galaxy
    sed_model: TBD
    spatial_model: knots
    subtype: knots
  disk_basic:
    MW_extinction: F19
    internal_extinction: CCM
    parent: galaxy
    sed_model: tophat
    spatial_model: sersic2D
    subtype: disk
  gaia_star:
    area_partition: None
    butler_parameters:
      collections: HSC/defaults
      dstype: gaia_dr2_20200414
    data_file_type: butler_refcat
    sed_method: use_lut
  galaxy:
    area_partition:
      nside: 32
      ordering: ring
      type: healpix
    attribute_aliases:
      size_knots_true: size_disk_true
      size_minor_knots_true: size_minor_disk_true
    composite:
      bulge: required
      disk: required
      knots: optional
    data_file_type: parquet
    file_template: galaxy_(?P<healpix>\d+).parquet
    flux_file_template: galaxy_flux_(?P<healpix>\d+).parquet
  knots_basic:
    MW_extinction: F19
    internal_extinction: CCM
    parent: galaxy
    sed_model: tophat
    spatial_model: knots
    subtype: knots
  snana:
    area_partition:
      nside: 32
      ordering: ring
      type: healpix
    data_file_type: parquet
    file_template: snana_(?P<healpix>\d+).parquet
    internal_extinction: None
    sed_model: snana
  sncosmo:
    MW_extinction: F19
    area_partition:
      nside: 32
      ordering: ring
      type: healpix
    data_file_type: parquet
    file_template: pointsource_(?P<healpix>\d+).parquet
    internal_extinction: None
    sed_model: sncosmo
  star:
    MW_extinction: F19
    area_partition:
      nside: 32
      ordering: ring
      type: healpix
    data_file_type: parquet
    file_template: pointsource_(?P<healpix>\d+).parquet
    flux_file_template: pointsource_flux_(?P<healpix>\d+).parquet
    internal_extinction: None
    sed_file_root_env_var: SIMS_SED_LIBRARY_DIR
    sed_model: file_nm
provenance:
  inputs:
    galaxy_truth: roman_rubin_2023_v1.1.2_elais
    sn_truth: /global/cfs/projectdirs/lsst/www/DESC_TD_PUBLIC/Roman+DESC/PQ+HDF5_ROMAN+LSST_LARGE/
    star_truth: /pscratch/sd/j/jrbogart/desc/UW_star_catalog/
  skyCatalogs_repo:
    git_branch: main
    git_hash: 8318bbf88e3f01b29d071c34e07026d73a768e82
    git_status:
    - UNCOMMITTED_FILES
    - UNTRACKED_FILES
  versioning:
    code_version: 1.7.0-rc2
    schema_version: 1.2.0
    diffmah: 0.4.2
    diffsky: 0.1.1
    diffstar: 0.2.2
    dsps: 0.3.4
    lsstdesc-diffsky: 0.1.6.dev46+g0b637a0
# skycatalog_root: /lus/eagle/projects/RomanDESC/roman_rubin_cats_v1.1.2_faint
skycatalog_root: /hpc/group/cosmology/OpenUniverse2024/roman_rubin_cats_v1.1.2_faint
