# Import just roman_imsim so we can access the registered template
modules:
    - roman_imsim

# Start with the default.yaml file, which we will modify below
template: roman_imsim_default

output.type: RomanASDF
output.file_name.format: "Roman_WAS_truth_%s_%i_%i.asdf"
