name: End-to-end test

on:
  push:
    # branches:
    #  - main
  pull_request:


jobs:
  build:
    name: Set up
    runs-on: ubuntu-latest
    defaults:
        run:
            # cf. https://github.com/conda-incubator/setup-miniconda#important
            shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Checkout LFS objects
      run: |
        git lfs install
        git clone https://github.com/DukeCosmology/SimHackJune2025

    - name: Install package (editable)
      run: pip install .

    - name: Run config files
      run: |
        galsim config/was.yaml