name: End-to-end test

on:
  push:
    # branches:
    #  - main
  pull_request:


jobs:
  build:
    name: Set up
    runs-on: ubuntu-latest
    defaults:
        run:
            # cf. https://github.com/conda-incubator/setup-miniconda#important
            shell: bash -l {0}

    env:
      VIRTUAL_ENV: .venv

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Checkout LFS objects
      run: |
        git lfs install
        git clone https://github.com/DukeCosmology/SimHackJune2025
        cd SimHackJune2025
        git checkout reference
        cd -

    - name: Snoop
      run: |
        ls .
        ls ..

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v3
      with:
          activate-environment: test
          python-version: "3.12"

    - name: Install packages on conda
      run: |
        conda update -n base conda
        conda install -c conda-forge galsim
        conda install -c conda-forge lsstdesc-diffsky

    - name: Install package
      run: |
        pip install --upgrade pip uv
        uv pip install git+https://github.com/LSSTDESC/skyCatalogs@gaia_lsst
        uv pip install .

    - name: Run config files
      run: |
        cd SimHackJune2025
        galsim hack.yaml
        cd -

    - name: Run end-to-end tests
      run: |
        pytest tests/test_e2e.py
