name: End-to-end test

on:
  push:
    # branches:
    #  - main
  pull_request:


jobs:
  build:
    name: Set up
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Checkout LFS objects
      run: git clone https://github.com/DukeCosmology/SimHackJune2025

    - name: Run config files
      run: |
        galsim config/was.yaml